/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Banco.Conexao;
import Controle.BaixaEstoqueDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.BaixaEstoque;



/**
 *
 * @author Abel
 */
public class FrmBaixaEstoque extends javax.swing.JFrame {

     
     //Objeto criado para ter acesso aos metodos para controle do banco
     BaixaEstoqueDAO baixaestoqueDAO = new BaixaEstoqueDAO();
     
     //Objeto criado para interação com os dados encapsulados
     BaixaEstoque baixaestoque = new BaixaEstoque();
    
    Connection conexao;
     //MenuPrincipal nome = new MenuPrincipal();
    
    int idFuncionario;
    
    
    
    /**
     * Creates new form FrmBaixaEstoque
     */
    public FrmBaixaEstoque() {
        initComponents();
        
        
        //lblnome.setText(nome.lblUser.getText());
        
        
        
       
        carregaCBOProdutos();
       
        //dadosCBOProdutos();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodBarra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboProdutos = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sfQtde = new com.toedter.components.JSpinField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConfirmarItens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCodBarra.setFont(new java.awt.Font("Dialog", 0, 18));
        txtCodBarra.setToolTipText("Código do cliente");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel7.setText("Estoque Atual:");

        cboProdutos.setFont(new java.awt.Font("Dialog", 0, 18));
        cboProdutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cboProdutos.setToolTipText("Selecione um Produto");
        cboProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboProdutosMouseClicked(evt);
            }
        });
        cboProdutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProdutosItemStateChanged(evt);
            }
        });
        cboProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProdutosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel8.setText("Produto:");

        txtEstoque.setEditable(false);
        txtEstoque.setFont(new java.awt.Font("Dialog", 0, 18));
        txtEstoque.setToolTipText("Código do cliente");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel9.setText("Quantidade:");

        sfQtde.setToolTipText("Indique uma quantidade");
        sfQtde.setMinimum(1);
        sfQtde.setValue(1);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel12.setText("Cod. Barra:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel6.setText("Funcionário:");

        lblnome.setFont(new java.awt.Font("Dialog", 0, 18));
        lblnome.setForeground(new java.awt.Color(-16711936,true));
        lblnome.setText("Nome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnome)
                            .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(34, 34, 34)
                        .addComponent(cboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(sfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Serif", 1, 24));
        jLabel5.setText("Baixa Estoque");

        btnConfirmarItens.setFont(new java.awt.Font("Dialog", 0, 18));
        btnConfirmarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Confirmar 22 x 22.png"))); // NOI18N
        btnConfirmarItens.setText("Baixa Estoque");
        btnConfirmarItens.setToolTipText("Confirma o cliente");
        btnConfirmarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarItensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnConfirmarItens)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarItens)
                .addGap(18, 18, 18))
        );

        setSize(new java.awt.Dimension(562, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboProdutosMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_cboProdutosMouseClicked

    private void cboProdutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProdutosItemStateChanged

        dadosCBOProdutos();
}//GEN-LAST:event_cboProdutosItemStateChanged

    private void cboProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProdutosActionPerformed
        
        //carregaCBOProdutos();
        //dadosCBOProdutos();
}//GEN-LAST:event_cboProdutosActionPerformed

    private void btnConfirmarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarItensActionPerformed
        // TODO add your handling code here:
        
        if(sfQtde.getValue() > Integer.parseInt(txtEstoque.getText()))
        {

                            JOptionPane.showMessageDialog(null, "Estoque não suficiente", "Erro", JOptionPane.INFORMATION_MESSAGE);
                          


                        
        }     
        
        else if(!"".equals(txtCodBarra.getText()))
        {
            
            int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente dar baixa no estoque ?", "Baixa Estoque", JOptionPane.YES_NO_OPTION);
            
                if(resp == JOptionPane.YES_OPTION)
                {
 
                    baixaestoque.setQtdeEstoque(sfQtde.getValue());                    
                    baixaestoque.setCod_barra(txtCodBarra.getText());                  
                    baixaestoqueDAO.removerEstoque(baixaestoque);
                    baixaEstoque();
                             
                    JOptionPane.showMessageDialog(null, "Baixa Estoque realizada com sucesso!");
                    
                    dispose();
                    new FrmBaixaEstoque().setVisible(true);
                
                }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado");
        }
        
        
    }//GEN-LAST:event_btnConfirmarItensActionPerformed

    
    private void baixaEstoque(){
        
        baixaestoque.setCod_barra(txtCodBarra.getText());
        baixaestoque.setId_funcionario(idFuncionario);
        baixaestoque.setDescricao(cboProdutos.getSelectedItem().toString());
        baixaestoque.setQtdeEstoque(sfQtde.getValue());
        baixaestoqueDAO.baixaEstoque(baixaestoque);
        
      
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBaixaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBaixaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBaixaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBaixaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBaixaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarItens;
    private javax.swing.JComboBox cboProdutos;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblnome;
    private com.toedter.components.JSpinField sfQtde;
    private javax.swing.JTextField txtCodBarra;
    private javax.swing.JTextField txtEstoque;
    // End of variables declaration//GEN-END:variables


     private void carregaCBOProdutos()
    {
       try
       {
           
        this.conexao = Conexao.getConexao();
        String sql = "select descricao from produtos";
        PreparedStatement ps = this.conexao.prepareStatement(sql);
        ResultSet rsts = ps.executeQuery();
        while(rsts.next())
            
            cboProdutos.addItem(rsts.getString("descricao"));
              
   
       }
           
       catch (SQLException erro)
           
       {
               JOptionPane.showMessageDialog(null, "Erro ao carregar CBO Produtos " + erro);
           
       }
    }
     
     private void dadosCBOProdutos()
     {
        try
        {
            this.conexao = Conexao.getConexao();
            String sql = "select id, cod_barra, estoque  from produtos where descricao = ?";
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setString(1, String.valueOf(cboProdutos.getSelectedItem()));
            ResultSet rsts = ps.executeQuery();
            
            rsts.next();
            
            txtCodBarra.setText(rsts.getString("cod_barra"));
            txtEstoque.setText(rsts.getString("estoque"));
            
            
            
             rsts.close();
                    
        }
         catch(SQLException err)
          {
                JOptionPane.showMessageDialog(null, "Erro ao trazer dados CBO Produtos " + err);
          }
        
        
     }
     
     public void retornaUser(String user, int id_fun){
         
         lblnome.setText(user); 
         idFuncionario = id_fun;
         
         
         
     }
     
    
     
     
     
     
 
    

        
       
        
}


