/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Banco.Conexao;
import Relatorios.GeraRelatorio;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Abel
 */
public class FrmConsultaClienteDetalhe extends javax.swing.JFrame {
    
    Connection conexao;
    DateFormat dataFor = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat df = new DecimalFormat("###,##0.00");
    int idCliente;
    ResultSet resultadoCliente;
    
    
   

    /**
     * Creates new form FrmConsultaClienteDetalhe
     */
    public FrmConsultaClienteDetalhe() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTel1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTel2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNasc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        btnDetalhes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtVendasRealizadas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDataUltimaVenda = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtParcelasPendentes = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDivida = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtVencidas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtLucroGerado = new javax.swing.JTextField();
        btnRelatorio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        dtaInicial = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        dtaFinal = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        txtLucroGeradoPeriodo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtVendasRealizadasPeriodo = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Cliente Detalhe");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações do Cliente"));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Nome do Cliente:");

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeCliente.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setText("Tel Residencial:");

        txtTel1.setEditable(false);
        txtTel1.setBackground(new java.awt.Color(255, 255, 255));
        txtTel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setText("Tel Celular:");

        txtTel2.setEditable(false);
        txtTel2.setBackground(new java.awt.Color(255, 255, 255));
        txtTel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Data de Cadastro:");

        txtDataCadastro.setEditable(false);
        txtDataCadastro.setBackground(new java.awt.Color(255, 255, 255));
        txtDataCadastro.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Status");

        txtStatus.setEditable(false);
        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtStatus.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtStatus.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtStatusPropertyChange(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setText("Endereço:");

        txtEndereco.setEditable(false);
        txtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        txtEndereco.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel13.setText("Data Nascimento:");

        txtNasc.setEditable(false);
        txtNasc.setBackground(new java.awt.Color(255, 255, 255));
        txtNasc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNasc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNascPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Cidade:");

        txtCidade.setEditable(false);
        txtCidade.setBackground(new java.awt.Color(255, 255, 255));
        txtCidade.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtCidade.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCidadePropertyChange(evt);
            }
        });

        btnDetalhes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDetalhes.setForeground(new java.awt.Color(255, 0, 0));
        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalhes))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informções de Vendas"));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel14.setText("Vendas realizadas:");

        txtVendasRealizadas.setEditable(false);
        txtVendasRealizadas.setBackground(new java.awt.Color(255, 255, 255));
        txtVendasRealizadas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtVendasRealizadas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtVendasRealizadasPropertyChange(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel15.setText("Data Ultima Venda");

        txtDataUltimaVenda.setEditable(false);
        txtDataUltimaVenda.setBackground(new java.awt.Color(255, 255, 255));
        txtDataUltimaVenda.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtDataUltimaVenda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDataUltimaVendaPropertyChange(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setText("Parcelas Pendentes:");

        txtParcelasPendentes.setEditable(false);
        txtParcelasPendentes.setBackground(new java.awt.Color(255, 255, 255));
        txtParcelasPendentes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtParcelasPendentes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtParcelasPendentesPropertyChange(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setText("Divida Atual:");

        txtDivida.setEditable(false);
        txtDivida.setBackground(new java.awt.Color(255, 255, 255));
        txtDivida.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtDivida.setForeground(new java.awt.Color(255, 0, 0));
        txtDivida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDividaPropertyChange(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setText("Parcelas Vencidas:");

        txtVencidas.setEditable(false);
        txtVencidas.setBackground(new java.awt.Color(255, 255, 255));
        txtVencidas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtVencidas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtVencidasPropertyChange(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setText("Lucro gerado:");

        txtLucroGerado.setEditable(false);
        txtLucroGerado.setBackground(new java.awt.Color(255, 255, 255));
        txtLucroGerado.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtLucroGerado.setForeground(new java.awt.Color(0, 255, 0));
        txtLucroGerado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtLucroGeradoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVendasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataUltimaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLucroGerado, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParcelasPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtVendasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtParcelasPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDataUltimaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtLucroGerado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnRelatorio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(255, 0, 0));
        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Periodo"));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setText("De:");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("Até:");

        dtaFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtaFinalPropertyChange(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel23.setText("Lucro gerado:");

        txtLucroGeradoPeriodo.setEditable(false);
        txtLucroGeradoPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        txtLucroGeradoPeriodo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtLucroGeradoPeriodo.setForeground(new java.awt.Color(0, 255, 0));
        txtLucroGeradoPeriodo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtLucroGeradoPeriodoPropertyChange(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel24.setText("Vendas realizadas:");

        txtVendasRealizadasPeriodo.setEditable(false);
        txtVendasRealizadasPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        txtVendasRealizadasPeriodo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtVendasRealizadasPeriodo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtVendasRealizadasPeriodoPropertyChange(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 0, 0));
        btnOk.setText("ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(dtaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVendasRealizadasPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLucroGeradoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(109, 109, 109)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtLucroGeradoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(btnOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txtVendasRealizadasPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatusPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtStatusPropertyChange
    
    }//GEN-LAST:event_txtStatusPropertyChange

    private void txtNascPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNascPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascPropertyChange

    private void txtCidadePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCidadePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadePropertyChange

    private void txtLucroGeradoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtLucroGeradoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroGeradoPropertyChange

    private void txtVencidasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtVencidasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVencidasPropertyChange

    private void txtDividaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDividaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDividaPropertyChange

    private void txtParcelasPendentesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtParcelasPendentesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParcelasPendentesPropertyChange

    private void txtDataUltimaVendaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDataUltimaVendaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataUltimaVendaPropertyChange

    private void txtVendasRealizadasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtVendasRealizadasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendasRealizadasPropertyChange

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        parcVencidas(idCliente);
        lucroCliente(idCliente);
        nContas(idCliente);
        dividaParcPendentes(idCliente);
        ultimaVenda(idCliente);
       
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void txtLucroGeradoPeriodoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtLucroGeradoPeriodoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroGeradoPeriodoPropertyChange

    private void txtVendasRealizadasPeriodoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtVendasRealizadasPeriodoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendasRealizadasPeriodoPropertyChange

    private void dtaFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtaFinalPropertyChange
       
       
       
    }//GEN-LAST:event_dtaFinalPropertyChange

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        lucroVendasPeriodo(idCliente);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        geraRelConsultaClientes();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRelatorioActionPerformed

    public void retornaDados(String nome){
        
        try {
            this.conexao = Conexao.getConexao();
            
            String sql = "Select cl.id, cl.nome, cl.data, cl.status, cl.fone1, cl.fone2, cl.endereco, ci.nome cidade, cl.datanasc from clientes cl inner join"
                    + " cidades ci on cl.id_cidade = ci.id where cl.nome = ?";
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setString(1, nome);
            ResultSet rsts = ps.executeQuery();
            resultadoCliente = rsts;
            rsts.next();
            
               
            idCliente = (rsts.getInt("cl.id"));
            
            txtCidade.setText(rsts.getString("cidade"));
            txtTel1.setText(rsts.getString("cl.fone1"));
            txtTel2.setText(rsts.getString("cl.fone2"));
            txtNasc.setText(dataFor.format(rsts.getDate("cl.datanasc")));
            txtEndereco.setText(rsts.getString("cl.endereco"));
            txtNomeCliente.setText(rsts.getString("cl.nome"));
   
            txtDataCadastro.setText(dataFor.format(rsts.getDate("cl.data")));
            //txtParcelasPendentes.setText(rsts.getString("parcelas"));
            //txtDivida.setText(df.format(rsts.getDouble("divida")));
            
            if("R".equals(rsts.getString("cl.status"))){
                        txtStatus.setForeground(Color.green);
                        txtStatus.setText("Regular");
                    }else{
                        txtStatus.setForeground(Color.red);
                        txtStatus.setText("Irregular");
                    }
            
            this.setVisible(true);
            
            
        } catch (SQLException ex) {
         
            JOptionPane.showMessageDialog(null, "Nenhum dado resgistrado !", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }
    
    private void parcVencidas(int idcliente){
        
        try {
            this.conexao = Conexao.getConexao();
            
            String sql = "Select  COUNT(nparc) vencidas from fluxocaixa where data_vencto < date(now()) and pago = 'N' and id_cliente = ?";
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setInt(1, idcliente);
            ResultSet rsts = ps.executeQuery();
            
            if(rsts.next()){
                txtVencidas.setText(rsts.getString("Vencidas"));
            }else{
                txtVencidas.setText("0");
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    private void lucroCliente(int idcliente){
        
        try{
            
            this.conexao = Conexao.getConexao();
            
            String sql = "SELECT SUM(VLR_FINAL) LUCRO_GERADO FROM FLUXOCAIXA WHERE PAGO = 'S' AND OPERACAO = 'V' AND ID_CLIENTE = ?";
        
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setInt(1, idcliente);
            ResultSet rsts = ps.executeQuery();
            
            rsts.next();
            
            txtLucroGerado.setText(df.format(rsts.getDouble("LUCRO_GERADO")));
            
            
            
        }catch(SQLException err){
            
        }
            
    }
    
    private void nContas(int idcliente){
        
        try {
            this.conexao = Conexao.getConexao();
            
            String sql = "Select count(id) nvendas from venda_cab where id_cliente = ?";
        
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setInt(1, idcliente);
            ResultSet rsts = ps.executeQuery();
            
            rsts.next();
            
            txtVendasRealizadas.setText(rsts.getString("nvendas"));
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void dividaParcPendentes(int idCliente){
        
        try {
            this.conexao = Conexao.getConexao();
            
            String sql = "SELECT SUM(VLR_PARC) DIVIDA_ATUAL, COUNT(NPARC) PARCELAS_PENDENTES FROM FLUXOCAIXA "
                    + "WHERE PAGO = 'N' AND OPERACAO = 'V' AND ID_CLIENTE = ?";
        
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setInt(1, idCliente);
            ResultSet rsts = ps.executeQuery();
            
            rsts.next();
            
            txtDivida.setText(rsts.getString("DIVIDA_ATUAL"));
            txtParcelasPendentes.setText(rsts.getString("PARCELAS_PENDENTES"));
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void ultimaVenda(int idCliente){
        
            try {
            this.conexao = Conexao.getConexao();
            
            String sql = "Select data from venda_cab where id_cliente = ?";
        
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setInt(1, idCliente);
            ResultSet rsts = ps.executeQuery();
            
            rsts.last();
            
            txtDataUltimaVenda.setText(dataFor.format(rsts.getDate("data")));
     
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    private void lucroVendasPeriodo(int idCliente){
        
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        
       try{ 
        String sql = "SELECT SUM(VLR_FINAL) LUCRO_GERADO_PERIODO FROM FLUXOCAIXA WHERE PAGO = 'S' AND OPERACAO = 'V' AND " +
                     "DATA_PGTO >= ? AND DATA_PGTO <= ? and id_cliente = ?";
        
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setString(1, format.format(dtaInicial.getDate()));
            ps.setString(2, format.format(dtaFinal.getDate()));
            ps.setInt(3, idCliente);
            ResultSet rsts = ps.executeQuery();
            
            rsts.last();
            
            txtLucroGeradoPeriodo.setText(df.format(rsts.getDouble("LUCRO_GERADO_PERIODO")));
            
            String sql2 = "select count(id) vendas from venda_cab where data >= ? and data <= ? and id_cliente = ?"; 
            PreparedStatement ps2 = this.conexao.prepareStatement(sql2);
            ps2.setString(1, format.format(dtaInicial.getDate()));
            ps2.setString(2, format.format(dtaFinal.getDate()));
            ps2.setInt(3, idCliente);
            ResultSet rsts2 = ps2.executeQuery();

            rsts2.next();

            txtVendasRealizadasPeriodo.setText(rsts2.getString("vendas"));
     
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    private void geraRelConsultaClientes(){
        
        try {
            
            
            
            
            this.conexao = Conexao.getConexao();
            
            String sql = "Select cl.id, cl.nome, cl.data, cl.uf, cl.fone1, cl.fone2, CONCAT_WS(', ', cl.endereco, cl.numero) endereco, ci.nome cidade, cl.datanasc,"
                    + " CASE status WHEN 'R' THEN 'Regular'"
                    + " ELSE 'Irregular' END status from clientes cl inner join"
                    + " cidades ci on cl.id_cidade = ci.id where cl.nome = ?";
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ps.setString(1, txtNomeCliente.getText());
            ResultSet rsts = ps.executeQuery();
            
            JRResultSetDataSource tst= new JRResultSetDataSource(rsts);
            JasperReport jr = (JasperReport)JRLoader.loadObject(getClass().getResource("/Relatorios/relConsultaClientes.jasper"));
            Map map = new HashMap();
            
            map.put("vendasRealizadas", Integer.parseInt(txtVendasRealizadas.getText()));
            map.put("parcelasPendentes", Integer.parseInt(txtParcelasPendentes.getText()));
            map.put("parcelasVencidas", Integer.parseInt(txtVencidas.getText()));
            map.put("dataUltimaVenda", txtDataUltimaVenda.getText());
            map.put("lucroGerado", txtLucroGerado.getText());
            map.put("dividaAtual", txtDivida.getText());
            
            JasperPrint jp = JasperFillManager.fillReport(jr,map,tst);
            new GeraRelatorio().verRelat("Relatório de Consulta de Clientes", jp);
            
        } catch (JRException ex) {
            Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        
    }
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaClienteDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultaClienteDetalhe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRelatorio;
    private com.toedter.calendar.JDateChooser dtaFinal;
    private com.toedter.calendar.JDateChooser dtaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtDataUltimaVenda;
    private javax.swing.JTextField txtDivida;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLucroGerado;
    private javax.swing.JTextField txtLucroGeradoPeriodo;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtParcelasPendentes;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTel1;
    private javax.swing.JTextField txtTel2;
    private javax.swing.JTextField txtVencidas;
    private javax.swing.JTextField txtVendasRealizadas;
    private javax.swing.JTextField txtVendasRealizadasPeriodo;
    // End of variables declaration//GEN-END:variables
}
