/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLogin.java
 *
 * Created on 07/03/2014, 01:19:08
 */
package Formularios;

import Banco.BancoTabelas;
import Banco.Conexao;
import Utilitarios.SalvaProps;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Abel
 */
public class FrmLogin extends javax.swing.JFrame {
    
    Connection conexao;

    String Tema; 
    
    /** Creates new form FrmLogin */
    public FrmLogin() {
        initComponents();
        
        

        //Seta o fundo pra branco
        this.setBackground(Color.WHITE);
           
        
        try {
                
            //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaOrangeMetallicLookAndFeel");
          // UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            
            //Cria o banco e as tabelas caso não existam
            BancoTabelas cria = new BancoTabelas();
            Conexao.CriaBanco();
            cria.CriaTabelas();
            

            //criarEntradas();
            
            //Método responsável por trazer o nome de usuário que está salvo
           puxaConfs();
            
            //Dois métodos responsáveis por verificar e criar um usuário caso não exista nenhum no banco de dados
            cria(criaUserVerifiquer());
            
             
      
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
          
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chbSalvarUser = new javax.swing.JCheckBox();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A.R.A. Sistemas para Salão de Beleza");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(-1,true));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36));
        jLabel1.setText("Usuário:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 48));
        jLabel3.setForeground(new java.awt.Color(-65536,true));
        jLabel3.setText("Entrar");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36));
        jLabel2.setText("Senha:");

        btnLogar.setBackground(new java.awt.Color(255, 255, 255));
        btnLogar.setFont(new java.awt.Font("Dialog", 0, 24));
        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 24));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/LOGO SISTEMA.png"))); // NOI18N

        jLabel5.setText("Versão 1.0");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14));
        jLabel6.setForeground(new java.awt.Color(-16776961,true));
        jLabel6.setText("Esqueci minha senha");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        chbSalvarUser.setBackground(new java.awt.Color(204, 204, 204));
        chbSalvarUser.setText("Salvar Usuário");

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(chbSalvarUser)
                    .addComponent(txtUsuario)
                    .addComponent(txtSenha))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(chbSalvarUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLogar)
                                    .addComponent(btnCancelar))))))
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(998, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
       
        //Método responsável por logar no Sistema
        logar();
        
    }//GEN-LAST:event_btnLogarActionPerformed

    
    
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair ?", "Sair", JOptionPane.YES_NO_OPTION);
        
            if(resp == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        //Inicia o form para a recuperação da senha
        new RecupSenha().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
            logar();
    }//GEN-LAST:event_txtSenhaActionPerformed

    //Método responsável por salvar o nome de usuário, caso ele tenha marcado a checkbox 'Salvar Usuário'
    private void salvaUser(String usuario){
        
        SalvaProps props = new SalvaProps();
        
        if(chbSalvarUser.isSelected() == true){
            
            
            props.salvaProp("salvaUsuario", usuario);
            props.salvaProp("salvaChbUsuario", "true");
                        
  
        }else if(chbSalvarUser.isSelected() == false){ //Condição usada quando o usuário desmarca a checkbox, e entra no sistema

            props.salvaProp("salvaUsuario", "");
            props.salvaProp("salvaChbUsuario", "false");
        }
        
        
    }
    
    //Puxa configurações utilizadas no inicio do sistema
    private void puxaConfs(){
        
            SalvaProps props = new SalvaProps();
           
            txtUsuario.setText(props.puxaProp("salvaUsuario"));

            chbSalvarUser.setSelected(Boolean.parseBoolean(props.puxaProp("salvaChbUsuario")));     
                      
                
    }
    
    private void logar(){
        try {
        this.conexao = Conexao.getConexao();
        
        String sql = "Select usuario, senha, nivel, id_funcionario, funcionario from usuarios where usuario = ? and senha = ?";
        PreparedStatement ps = this.conexao.prepareStatement(sql);
        ps.setString(1, txtUsuario.getText());
        ps.setString(2, String.valueOf(txtSenha.getPassword()));
        ResultSet rst = ps.executeQuery();
        
        rst.next();
        
         
        if(rst.getString("usuario").equalsIgnoreCase(txtUsuario.getText()) && (rst.getString("senha").equals(txtSenha.getText()))){
            
           MenuPrincipal mp = new MenuPrincipal();
           mp.acesso(rst.getString("nivel"), rst.getString("funcionario"), rst.getInt("id_funcionario"));
           mp.setVisible(true);
           salvaUser(txtUsuario.getText());
           this.setVisible(false);
            
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao efetuar login, Usuário ou Senha incorretos." + "\n" +
                                           "Diferenciar LETRAS MAIÚSCULAS E MINÚSCULAS.", "Erro login", 0);
            
        }   
        
       
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao efetuar login, Usuário ou Senha incorretos." + "\n" +
                                           "Diferenciar LETRAS MAIÚSCULAS E MINÚSCULAS.", "Erro login", 0);

        }
    }
    
    //Este método verifica se tem usuário criando no sistema, se NÃO tiver, retorna 'true'
    private boolean criaUserVerifiquer(){
        
        boolean retorno = false;
        
        try{
            

            this.conexao = Conexao.getConexao();
            String sql = "select id from usuarios LIMIT 1";
            PreparedStatement ps = this.conexao.prepareStatement(sql);
            ResultSet rsts = ps.executeQuery();
            
            rsts.next();
            rsts.getInt("id");
            
          
           
            
        }catch(SQLException err){
        
            retorno = true;
                
        }
        
        return retorno;
        
    }
    
    
    //Este método permite criar um primeiro usuário caso o método 'criaUserVerifiquer' retorne true
    private void cria(boolean retorno){
        
        if(retorno == true){
      
                try {


                    Calendar c = Calendar.getInstance();
                    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

                    JOptionPane.showMessageDialog(null, "Não existe um usuário cadastrado !" + "\n" +
                            "Será criado um usuário automaticamente !", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                    String resp = JOptionPane.showInputDialog(null, "Insira um usuário", "Cadastro" , JOptionPane.INFORMATION_MESSAGE);
                    String senha = JOptionPane.showInputDialog(null, "Insira uma senha", "Cadastro" , JOptionPane.INFORMATION_MESSAGE);

                    String sql2 = "insert into usuarios (usuario, senha, id_funcionario, funcionario, nivel, data) " +
                            "values (?, ?, ?, ?, ?, ?)";
                    PreparedStatement ps2 = this.conexao.prepareStatement(sql2);
                    ps2.setString(1, resp);
                    ps2.setString(2, senha);
                    ps2.setInt(3, 1);
                    ps2.setString(4, "administrador");
                    ps2.setString(5, "A");
                    ps2.setString(6, df.format(c.getTime()));
                    ps2.execute();

                    JOptionPane.showMessageDialog(null, "Primeiro cadastro efetuado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);


                } catch (SQLException ex) {
                    Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }    
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmLogin().setVisible(true);
                
                
          
                
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLogar;
    private javax.swing.JCheckBox chbSalvarUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
