/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmTemas.java
 *
 * Created on 08/05/2014, 20:01:31
 */
package Formularios;
import javax.swing.*;


     


/**
 *
 * @author Formigao
 */
public class FrmTemas extends javax.swing.JFrame {
    

   
    String Tema ;
    

    /** Creates new form FrmTemas */
    public FrmTemas() {
        initComponents();
        
    }
    
    

            

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTemas = new javax.swing.ButtonGroup();
        rdbTema1 = new javax.swing.JRadioButton();
        rdbTema2 = new javax.swing.JRadioButton();
        rdbTema3 = new javax.swing.JRadioButton();
        rdbTema4 = new javax.swing.JRadioButton();
        rdbTema5 = new javax.swing.JRadioButton();
        rdbTema9 = new javax.swing.JRadioButton();
        rdbTema10 = new javax.swing.JRadioButton();
        rdbTema7 = new javax.swing.JRadioButton();
        rdbTema8 = new javax.swing.JRadioButton();
        rdbTema6 = new javax.swing.JRadioButton();
        rdbTema14 = new javax.swing.JRadioButton();
        rdbTema15 = new javax.swing.JRadioButton();
        rdbTema12 = new javax.swing.JRadioButton();
        rdbTema13 = new javax.swing.JRadioButton();
        rdbTema11 = new javax.swing.JRadioButton();
        btnVisualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Temas");

        btngTemas.add(rdbTema1);
        rdbTema1.setText("Tema 1");
        rdbTema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema1ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema2);
        rdbTema2.setText("Tema 2");
        rdbTema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema2ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema3);
        rdbTema3.setText("Tema 3");
        rdbTema3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema3ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema4);
        rdbTema4.setText("Tema 4");
        rdbTema4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema4ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema5);
        rdbTema5.setText("Tema 5");
        rdbTema5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema5ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema9);
        rdbTema9.setText("Tema 9");
        rdbTema9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema9ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema10);
        rdbTema10.setText("Tema 10");
        rdbTema10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema10ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema7);
        rdbTema7.setText("Tema 7");
        rdbTema7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema7ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema8);
        rdbTema8.setText("Tema 8");
        rdbTema8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema8ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema6);
        rdbTema6.setText("Tema 6");
        rdbTema6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema6ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema14);
        rdbTema14.setText("Tema 14");
        rdbTema14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema14ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema15);
        rdbTema15.setText("Tema 15");
        rdbTema15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema15ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema12);
        rdbTema12.setText("Tema 12");
        rdbTema12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema12ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema13);
        rdbTema13.setText("Tema 13");
        rdbTema13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema13ActionPerformed(evt);
            }
        });

        btngTemas.add(rdbTema11);
        rdbTema11.setText("Tema 11");
        rdbTema11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTema11ActionPerformed(evt);
            }
        });

        btnVisualizar.setText("VISUALIZAR");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        jTextField1.setText("Teste Tema");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("TESTE TESTE TESTE TESTE TESTE TESTE TESTE TESTE ");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1)
                        .addComponent(jLabel1))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbTema5)
                            .addComponent(rdbTema4)
                            .addComponent(rdbTema3)
                            .addComponent(rdbTema2)
                            .addComponent(rdbTema1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbTema10)
                            .addComponent(rdbTema9)
                            .addComponent(rdbTema8)
                            .addComponent(rdbTema7)
                            .addComponent(rdbTema6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbTema15)
                            .addComponent(rdbTema14)
                            .addComponent(rdbTema13)
                            .addComponent(rdbTema12)
                            .addComponent(rdbTema11))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbTema11)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema12)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema13)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema14)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbTema6)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema7)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema8)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema9)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbTema1)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema2)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema3)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema4)
                                .addGap(18, 18, 18)
                                .addComponent(rdbTema5)))
                        .addGap(29, 29, 29)
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbTema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema2ActionPerformed
        // TODO add your handling code here:
       Tema = "de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel";
        
    }//GEN-LAST:event_rdbTema2ActionPerformed

    private void rdbTema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema1ActionPerformed
           
      
       Tema = "de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel";         
    
        
    }//GEN-LAST:event_rdbTema1ActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
     
          
        
    
        Temas();
      
      
        
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void rdbTema3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema3ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel";
        
        
    }//GEN-LAST:event_rdbTema3ActionPerformed

    private void rdbTema4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema4ActionPerformed
        // TODO add your handling code here:
            //Tema = "com.jtattoo.plaf.acryl.AcrylLookAndFeel";
           // Tema = "de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel";
            Tema = "de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel";
    }//GEN-LAST:event_rdbTema4ActionPerformed

    private void rdbTema5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema5ActionPerformed
        // TODO add your handling code here:
        Tema = " de.javasoft.plaf.synthetica.SyntheticaBlueSteelLookAndFeel";
    }//GEN-LAST:event_rdbTema5ActionPerformed

    private void rdbTema6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema6ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaGreenDreamLookAndFeel";
    }//GEN-LAST:event_rdbTema6ActionPerformed

    private void rdbTema7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema7ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaMauveMetallicLookAndFeel";
    }//GEN-LAST:event_rdbTema7ActionPerformed

    private void rdbTema8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema8ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaOrangeMetallicLookAndFeel";
    }//GEN-LAST:event_rdbTema8ActionPerformed

    private void rdbTema9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema9ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel";
    }//GEN-LAST:event_rdbTema9ActionPerformed

    private void rdbTema10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema10ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel";
    }//GEN-LAST:event_rdbTema10ActionPerformed

    private void rdbTema11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema11ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaWhiteVisionLookAndFeel";
    }//GEN-LAST:event_rdbTema11ActionPerformed

    private void rdbTema12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema12ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel";
        
    }//GEN-LAST:event_rdbTema12ActionPerformed

    private void rdbTema13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema13ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaSimple2DLookAndFeel";
    }//GEN-LAST:event_rdbTema13ActionPerformed

    private void rdbTema14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema14ActionPerformed
        // TODO add your handling code here:
          Tema = "de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel";
    }//GEN-LAST:event_rdbTema14ActionPerformed

    private void rdbTema15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTema15ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaWhiteVisionLookAndFeel";
    }//GEN-LAST:event_rdbTema15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            

            public void run() {
                new FrmTemas().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    public javax.swing.ButtonGroup btngTemas;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JRadioButton rdbTema1;
    private javax.swing.JRadioButton rdbTema10;
    private javax.swing.JRadioButton rdbTema11;
    private javax.swing.JRadioButton rdbTema12;
    private javax.swing.JRadioButton rdbTema13;
    private javax.swing.JRadioButton rdbTema14;
    private javax.swing.JRadioButton rdbTema15;
    private javax.swing.JRadioButton rdbTema2;
    private javax.swing.JRadioButton rdbTema3;
    private javax.swing.JRadioButton rdbTema4;
    private javax.swing.JRadioButton rdbTema5;
    private javax.swing.JRadioButton rdbTema6;
    private javax.swing.JRadioButton rdbTema7;
    private javax.swing.JRadioButton rdbTema8;
    private javax.swing.JRadioButton rdbTema9;
    // End of variables declaration//GEN-END:variables

public void Temas()
    { 
        try
        {
            
            UIManager.setLookAndFeel(Tema);
            SwingUtilities.updateComponentTreeUI(this);
            
        }
        catch(Exception erro)         
        {
                    
               JOptionPane.showMessageDialog(null, erro);
        }
    }    


     

    
    
}
