/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmVendaVista.java
 *
 * Created on 06/03/2014, 14:19:40
 */
package Formularios;

import Controle.VendasDAO;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Currency;
import java.util.Locale;
import javax.swing.JOptionPane;
import modelo.Vendas;

/**
 *
 * @author Abel
 */
public class FrmVendaVista extends javax.swing.JFrame {
    
    DecimalFormat formater = new DecimalFormat("##,##0.00"); 
    int idCliente, idVenda;

    /** Creates new form FrmVendaVista */
    public FrmVendaVista() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmação de Venda com Dinheiro");
        setResizable(false);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 36));
        jLabel18.setText("Total:");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 36));
        jLabel19.setText("Dinheiro:");

        txtDinheiro.setFont(new java.awt.Font("Dialog", 0, 36));
        txtDinheiro.setText("0");
        txtDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDinheiroActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Dialog", 1, 36));
        txtTotal.setForeground(new java.awt.Color(-65536,true));
        txtTotal.setText("0");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 36));
        jLabel21.setText("Troco:");

        txtTroco.setEditable(false);
        txtTroco.setBackground(new java.awt.Color(255, 255, 255));
        txtTroco.setFont(new java.awt.Font("Dialog", 0, 36));
        txtTroco.setText("0");

        btnConfirmar.setFont(new java.awt.Font("Dialog", 1, 36));
        btnConfirmar.setForeground(new java.awt.Color(-65536,true));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTroco)
                            .addComponent(txtDinheiro)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDinheiro)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtTroco))
                .addGap(30, 30, 30)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        setSize(new java.awt.Dimension(451, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
     
}//GEN-LAST:event_txtTotalActionPerformed

    private void txtDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDinheiroActionPerformed
        troco();
    }//GEN-LAST:event_txtDinheiroActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
      try { 
        
        double total = Double.parseDouble(String.valueOf(formater.parse(txtTotal.getText())));
        double din = Double.parseDouble(String.valueOf(formater.parse(txtDinheiro.getText())));
        
        if(din > total){
                Vendas vendas = new Vendas();
                VendasDAO vendasDAO = new VendasDAO();
                
                vendas.setId_cliente(idCliente);
                vendas.setId_venda(idVenda);
                vendas.setTipo_pgto("Dinheiro");
                vendas.setVlr_final(total);
                vendas.setStatusVendaCab("R");
                vendasDAO.atualizaVendaCab(vendas);
                vendasDAO.confirmaFluxoCaixa(vendas);
                JOptionPane.showMessageDialog(null, "Venda registrada com sucesso", "Venda", JOptionPane.INFORMATION_MESSAGE);
                new FrmVendas().dispose();
        
            
        }else{
            JOptionPane.showMessageDialog(null, "O valor inserido não confere com o pago !", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
            } catch (ParseException ex) {
               // Logger.getLogger(FrmVendaVista.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
        
        this.dispose();
                
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    
    public Double retornaTotal(Double valor, int cliente, int venda){
        
        txtTotal.setText(formater.format(valor));
        idCliente = cliente;
        idVenda = venda;
        this.setVisible(true);
        
        return valor;
    }
    
     private void troco(){
        
        try{
        
        //Seta o local para a Moeda brasileira
        formater.setCurrency(Currency.getInstance(new Locale("pt", "BR")));
        
        //Remove a virgula da moeda brasileira, obrigatório passar para String
        Double din = Double.parseDouble(String.valueOf(formater.parse(txtDinheiro.getText())));
        Double total = Double.parseDouble(String.valueOf(formater.parse(txtTotal.getText()))); 
        
        //Passa a moeda para o formato Americano, para trabalhas com as contas
     
        
        if(din > total){
            
            
            din = din - total;
           
            txtTroco.setText(String.valueOf(formater.format(din)));
  
        }
        
        }catch(ParseException err){
            JOptionPane.showMessageDialog(null,"Erro ao converter moeda TROCO " + err);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmVendaVista().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
