/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuPrincipal.java
 *
 * Created on 01/12/2013, 12:26:35
 */
package Formularios;





import Relatorios.GeraRelatorio;
import Utilitarios.SalvaProps;
import Utilitarios.Backup;
import Utilitarios.Notificacoes;
import Utilitarios.TrayIcones;
import java.awt.Cursor;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat; 
import java.util.Calendar; 
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JasperPrint; 








/**
 *
 * @author Abel
 */
public class MenuPrincipal extends javax.swing.JFrame {

   
    
     
     Connection conexao;
     TrayIcones icones = new TrayIcones();
     int idFuncionario;
     String Tema; 
     SalvaProps props = new SalvaProps();
     String sms;
    
     
    
    /** Creates new form MenuPrincipal */
     

    public MenuPrincipal() {
        
            
            initComponents();
            
           
            
            //Carrega algumas configurações pós inicio do Sistema
            puxaConfs();          
                        
            //Faz o menu principal ficar de tela cheia e adiciona Background
            this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
            
           
            //Componente de Calendário, inicia invisivel, aparece só quando clica na data no rodapé do sistema
            caData.setVisible(false);
            
            //Coloca um menu na barra de notificações
            icones.tray(this);
            
            //Verifica se existe parcelas atrazadas
            verificaParcs();
            
            //Coloca um icone no form
            icones.icone(this);
            
            //Inicia a hora do Sistema
            timerHora.start();
  
    }

    public JMenuItem getMenuClientes() {
        return menuItemCadClientes;
    }

    public void setMenuClientes(JMenuItem MenuClientes) {
        this.menuItemCadClientes = MenuClientes;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timerHora = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAcesso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSO = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        caData = new com.toedter.calendar.JCalendar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnAgendaAtalho = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnNoficacoes = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();
        menuItemCadCidades = new javax.swing.JMenuItem();
        menuItemCadCargos = new javax.swing.JMenuItem();
        menuItemCadFuncio = new javax.swing.JMenuItem();
        menuItemCadClientes = new javax.swing.JMenuItem();
        menuItemCadFornece = new javax.swing.JMenuItem();
        menuItemProdutos = new javax.swing.JMenuItem();
        menuItemServicos = new javax.swing.JMenuItem();
        menuItemUsers = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        menu_utilitarios = new javax.swing.JMenu();
        Menu_Temas = new javax.swing.JMenu();
        menuItem_Tema1 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        timerHora.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timerHoraOnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("A.R.A. Sistemas de Gerenciamento");
        setFocusCycleRoot(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Logado como:");

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 0, 0));
        lblUser.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nivel de Acesso:");

        lblAcesso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAcesso.setForeground(new java.awt.Color(0, 220, 69));
        lblAcesso.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sistema Operacional:");

        lblSO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSO.setForeground(new java.awt.Color(0, 0, 255));
        lblSO.setText("jLabel2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data:");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblData.setText("Data:");
        lblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAcesso)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblData)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUser)
                    .addComponent(jLabel2)
                    .addComponent(lblAcesso)
                    .addComponent(jLabel3)
                    .addComponent(lblSO)
                    .addComponent(jLabel4)
                    .addComponent(lblData)))
        );

        caData.setTodayButtonText("Hoje");
        caData.setTodayButtonVisible(true);

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Calendario 24x24.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator6);

        btnAgendaAtalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Calendario Add 24x24.png"))); // NOI18N
        btnAgendaAtalho.setToolTipText("");
        btnAgendaAtalho.setFocusable(false);
        btnAgendaAtalho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgendaAtalho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgendaAtalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaAtalhoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgendaAtalho);
        jToolBar1.add(jSeparator5);

        btnNoficacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/email lido 48x48.png"))); // NOI18N
        btnNoficacoes.setFocusable(false);
        btnNoficacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNoficacoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNoficacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoficacoesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNoficacoes);
        jToolBar1.add(jSeparator4);

        menu_cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Cadastros 32 x 32.png"))); // NOI18N
        menu_cadastros.setText("Cadastros");

        menuItemCadCidades.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemCadCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/City 16 x 16.png"))); // NOI18N
        menuItemCadCidades.setText("Cidades");
        menuItemCadCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadCidadesActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemCadCidades);

        menuItemCadCargos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuItemCadCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Cargo 16 x 16.png"))); // NOI18N
        menuItemCadCargos.setText("Cargos");
        menuItemCadCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadCargosActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemCadCargos);

        menuItemCadFuncio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menuItemCadFuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/User 2 16 x 16.png"))); // NOI18N
        menuItemCadFuncio.setText("Funcionários");
        menuItemCadFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadFuncioActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemCadFuncio);

        menuItemCadClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuItemCadClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/User 3 16 x 16.png"))); // NOI18N
        menuItemCadClientes.setText("Clientes");
        menuItemCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadClientesActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemCadClientes);

        menuItemCadFornece.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menuItemCadFornece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Fornecedor 16 x 16.png"))); // NOI18N
        menuItemCadFornece.setText("Fornecedores");
        menuItemCadFornece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadForneceActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemCadFornece);

        menuItemProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuItemProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Produtos 16 x 16.png"))); // NOI18N
        menuItemProdutos.setText("Produtos");
        menuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutosActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemProdutos);

        menuItemServicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItemServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Serviço 16 x 16.png"))); // NOI18N
        menuItemServicos.setText("Serviços");
        menuItemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemServicosActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemServicos);

        menuItemUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuItemUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/User 5 16 x 16.png"))); // NOI18N
        menuItemUsers.setText("Usuários");
        menuItemUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsersActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuItemUsers);

        jMenuBar1.add(menu_cadastros);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Movimentação 32 x 32.png"))); // NOI18N
        jMenu1.setText("Movimentação");

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Agenda 16 x 16.png"))); // NOI18N
        jMenuItem18.setText("Agenda");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem18);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Vendas 16 x 16.png"))); // NOI18N
        jMenuItem16.setText("Compras");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Pagamento 16 x 16.png"))); // NOI18N
        jMenuItem4.setText("Vendas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Contas Receber 16 x 16.png"))); // NOI18N
        jMenuItem17.setText("Contas à Receber");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem17);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Contas Pagar 16 x 16.png"))); // NOI18N
        jMenuItem8.setText("Contas à Pagar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Baixa Estoque 16 x16.png"))); // NOI18N
        jMenuItem3.setText("Baixa Estoque");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Consulta 32 x 32.png"))); // NOI18N
        jMenu3.setText("Consultas");

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Caixa registradora 16 x 16.png"))); // NOI18N
        jMenuItem19.setText("Fluxo Caixa");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Consulta Cliente 16 x 16.png"))); // NOI18N
        jMenuItem5.setText("Consulta Clientes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Consulta Baixa Estoque 16 x 16.png"))); // NOI18N
        jMenuItem9.setText("Consulta Baixa Estoque");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        MenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Relatotios 32 x 32.png"))); // NOI18N
        MenuRelatorios.setText("Relatórios");

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Relatorios 16 x 16.png"))); // NOI18N
        jMenuItem12.setText("Funcionários");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jMenuItem12);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Relatorios 16 x 16.png"))); // NOI18N
        jMenuItem15.setText("Clientes");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jMenuItem15);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Relatorios 16 x 16.png"))); // NOI18N
        jMenuItem11.setText("Fornecedores");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jMenuItem11);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Relatorios 16 x 16.png"))); // NOI18N
        jMenuItem13.setText("Produtos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Relatorios 16 x 16.png"))); // NOI18N
        jMenuItem14.setText("Serviços");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jMenuItem14);

        jMenuBar1.add(MenuRelatorios);

        menu_utilitarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Configurações 32 x 32.png"))); // NOI18N
        menu_utilitarios.setText("Configurações");

        Menu_Temas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        Menu_Temas.setText("Temas");

        menuItem_Tema1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        menuItem_Tema1.setText("Padrão");
        menuItem_Tema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_Tema1ActionPerformed(evt);
            }
        });
        Menu_Temas.add(menuItem_Tema1);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem20.setText("Black Moon");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem20);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem21.setText("Black Star");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem21);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem22.setText("Blue Ice");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem22);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem23.setText("Blue Moon");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem23);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem24.setText("Blue Steel");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem24);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem25.setText("Green Dream");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem25);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem26.setText("Mauve Metallic");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem26);

        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem27.setText("Orange Metallic");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem27);

        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem28.setText("Silver Moon");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem28);

        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Temas 16 x 16.png"))); // NOI18N
        jMenuItem29.setText("Sky Metallic");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        Menu_Temas.add(jMenuItem29);

        menu_utilitarios.add(Menu_Temas);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Backup 16 x 16.png"))); // NOI18N
        jMenuItem6.setText("Backup");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menu_utilitarios.add(jMenuItem6);

        jMenuBar1.add(menu_utilitarios);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/Sair 32 x 32.png"))); // NOI18N
        jMenu4.setText("Sair");

        jMenuItem1.setText("Logoff");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(caData, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(caData, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_Tema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_Tema1ActionPerformed

         Tema = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Deseja realmente mudar o tema? ", "Tema", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
                
     
    }//GEN-LAST:event_menuItem_Tema1ActionPerformed

    private void menuItemCadCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadCidadesActionPerformed
        CadastroCidades cadasCidades = new CadastroCidades();
        cadasCidades.setVisible(true);
    }//GEN-LAST:event_menuItemCadCidadesActionPerformed

    private void menuItemCadFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadFuncioActionPerformed
        new CadastroFuncionarios().setVisible(true);
    }//GEN-LAST:event_menuItemCadFuncioActionPerformed

    private void menuItemServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemServicosActionPerformed
       new CadastroServicos().setVisible(true);
    }//GEN-LAST:event_menuItemServicosActionPerformed

    private void menuItemUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsersActionPerformed
      new CadastroUsuarios().setVisible(true);
    }//GEN-LAST:event_menuItemUsersActionPerformed

    private void menuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutosActionPerformed
        // TODO add your handling code here:
        new CadastroProdutos().setVisible(true);
    }//GEN-LAST:event_menuItemProdutosActionPerformed

    private void menuItemCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadClientesActionPerformed
       
        // TODO add your handling code here:
              new CadastroClientes().setVisible(true);
        
    }//GEN-LAST:event_menuItemCadClientesActionPerformed

    private void menuItemCadCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadCargosActionPerformed
        // TODO add your handling code here:
        new CadastroCargos().setVisible(true);
    }//GEN-LAST:event_menuItemCadCargosActionPerformed

    private void menuItemCadForneceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadForneceActionPerformed
        // TODO add your handling code here:
          new CadastroFornecedores().setVisible(true);
    }//GEN-LAST:event_menuItemCadForneceActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        
    
             
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            GeraRelatorio rep = new GeraRelatorio(); 
            
            try
            { 
                rep.gerarRelatoriosFornecedores(); 
                
                
                //JRViewer viewer = new JRViewer(relat);
                //JasperViewer.viewReport(relat,false); 
             this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));   
                                      
                
            }
            catch (Exception e)
            { 
                e.printStackTrace(); 
            } 
             
            
    
       
              
       
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        GeraRelatorio rep = new GeraRelatorio(); 
        
        JasperPrint relat; 
        
        try
        {       this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                rep.gerarRelatoriosFuncionarios(); 
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
        catch (Exception e)
        { 
                e.printStackTrace(); 
        } 
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
           GeraRelatorio rep = new GeraRelatorio(); 
            
           JasperPrint relat; 
            
           try
           {    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                rep.gerarRelatoriosProdutos(); 
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); 
           }
           catch (Exception e)
           { 
                e.printStackTrace(); 
           } 
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
            GeraRelatorio rep = new GeraRelatorio(); 
            
            JasperPrint relat; 
            
            try
            {   this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                rep.gerarRelatoriosServicos();
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                
            }
            catch (Exception e)
            { 
                e.printStackTrace(); 
            } 
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
         // TODO add your handling code here:
         GeraRelatorio rep = new GeraRelatorio(); 
         
         try
         {      this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                rep.gerarRelatoriosClientes(); 
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
         }
         catch (Exception e)
         { 
                e.printStackTrace(); 
         }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new FrmVendas().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        new FrmContasReceber().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new FrmBackup().setVisible(true);
        
            
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente fazer logoff ?", "Logoff", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(resp == JOptionPane.YES_OPTION){
              
            this.dispose();
            new FrmLogin().setVisible(true);
            
            
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair ?", "Sair", JOptionPane.YES_NO_OPTION);
        
        if(resp == JOptionPane.YES_OPTION){
          
            //FrmLogin fl = new FrmLogin();
            //fl.setDefaultCloseOperation(EXIT_ON_CLOSE);
            if("S".equals(props.puxaProp("backupES"))){
                new Backup().backupEntraSaidoSistema();
            }
            System.exit(0);
        }   
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new FrmConsultaCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void timerHoraOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerHoraOnTime
            Calendar c = Calendar.getInstance();
            DateFormat datefor = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
            lblData.setText(datefor.format(c.getTime()));
    }//GEN-LAST:event_timerHoraOnTime

    private void lblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataMouseClicked
        caData.setVisible(true);
    }//GEN-LAST:event_lblDataMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        caData.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
            if(jToggleButton1.isSelected()){
                
                this.setResizable(false);
                this.setVisible(false);
                this.setVisible(true);
            }else{
                 this.setResizable(true);
                this.setVisible(false);
                this.setVisible(true);
            }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
       
        int state = 1;
        
        
        if(state == this.getState()){
            
            this.setVisible(false);
            
            
          
       }else{          
                      
        }
     
    }//GEN-LAST:event_formWindowStateChanged

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        new FrmCompras().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FrmBaixaEstoque be = new FrmBaixaEstoque();
        be.retornaUser(lblUser.getText(), idFuncionario);
        be.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new FrmConsultaBaixaEstoque().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
          
        //Quando clica com o botão fechar, dispara este evento 
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do Sistema", "Sair", JOptionPane.YES_NO_OPTION);
            
                if(resp == JOptionPane.YES_OPTION){
          
                  if("S".equals(props.puxaProp("backupES"))){
                        new Backup().backupEntraSaidoSistema();
                        
                    }
                 System.exit(0);
                }
                
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        new FrmAgenda().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new FrmConsultaFluxoCaixa().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
       new FrmContasPagar().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
         Tema = "de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
        
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
        
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
          Tema = "de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
            Tema = "de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaBlueSteelLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
         Tema = "de.javasoft.plaf.synthetica.SyntheticaGreenDreamLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
           Tema = "de.javasoft.plaf.synthetica.SyntheticaMauveMetallicLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                
                Temas();                
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
           Tema = "de.javasoft.plaf.synthetica.SyntheticaOrangeMetallicLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        Tema = "de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel";
         
         int resp =  JOptionPane.showConfirmDialog(null, "Este tema pode demorar alguns segundos para inicializar o sistema " + "\n" 
                                                        +"Deseja realmente mudar o tema? ", "MUDAR TEMA", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION){
               
                Temas();
                props.salvaProp("tema", Tema);
                
            }//Fim Se
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void btnNoficacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoficacoesActionPerformed
        
        new FrmNotificacoes2().mensagem(sms);
        btnNoficacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/email lido 48x48.png")));
        
    }//GEN-LAST:event_btnNoficacoesActionPerformed

    private void btnAgendaAtalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaAtalhoActionPerformed
        new FrmAgenda().setVisible(true);
    }//GEN-LAST:event_btnAgendaAtalhoActionPerformed

    public void acesso(String nivel, String user, int id_Fun){
     
        lblUser.setText(user);
        lblSO.setText(System.getProperty("os.name"));
        idFuncionario = id_Fun;
        
        
        if("C".equals(nivel)){
            
            menuItemCadCargos.setVisible(false);
            menuItemCadFuncio.setVisible(false);
            menuItemCadFornece.setVisible(false);
            menuItemUsers.setVisible(false);
            MenuRelatorios.setVisible(false);
            lblAcesso.setText("Comum");
        
            
        }else{
            lblAcesso.setText("Administrador");
        }
        
        
        
        
        
    }

    //Método que verifica as parcelas atrazadas e mostra popup
    private void verificaParcs(){
        
        Notificacoes notificacoes = new Notificacoes();
        int n = notificacoes.NotificarParcAtraz();
        if(n != 0){
            
            btnNoficacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagems/email 48x48.png")));
            sms = "A.R.A Sistemas Avisa - Existem clientes com parcelas atrazadas !!!";
            
            //sms = sms + "\n \n" + "Seja bem vindo a um teste no sistema";
                    
            
        }
        
    }
    
    
    
    
    //Método que Aplica o Tema Escolhido
    public void Temas()
    { 
        try
        {
            
            
            //Aplica o tema esclhido
            UIManager.setLookAndFeel(Tema);
            //Atualiza os forms
            SwingUtilities.updateComponentTreeUI(this);
            
            
            
        }
        catch(Exception erro)         
        {
                    
               JOptionPane.showMessageDialog(null, erro);
        }
    }    
   
    //Método que puxa as configurações salvas
     private void puxaConfs(){
        
             //Pega o tema salvo pelo usuário
             Tema = props.puxaProp("tema");
             //Aplica o tema
             Temas();
    
             if("S".equals(props.puxaProp("backupES"))){
                 new Backup().backupManual();
                
             }
             
     }
    
    
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            

            public void run() {
               
                    new MenuPrincipal().setVisible(true);
                    
           
                
            } 
                
                
        
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu Menu_Temas;
    private javax.swing.JButton btnAgendaAtalho;
    private javax.swing.JButton btnNoficacoes;
    private com.toedter.calendar.JCalendar caData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JLabel lblAcesso;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblSO;
    public javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem menuItemCadCargos;
    public javax.swing.JMenuItem menuItemCadCidades;
    private javax.swing.JMenuItem menuItemCadClientes;
    private javax.swing.JMenuItem menuItemCadFornece;
    private javax.swing.JMenuItem menuItemCadFuncio;
    private javax.swing.JMenuItem menuItemProdutos;
    private javax.swing.JMenuItem menuItemServicos;
    private javax.swing.JMenuItem menuItemUsers;
    private javax.swing.JMenuItem menuItem_Tema1;
    public javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenu menu_utilitarios;
    private org.netbeans.examples.lib.timerbean.Timer timerHora;
    // End of variables declaration//GEN-END:variables


}
